DROP TABLE RBT_TRIGGERS;
DROP TABLE RBT_CALENDARS;

-- DROP TABLE RBT_TRIGGERS;
CREATE TABLE RBT_TRIGGERS(TRIGGER_GROUP VARCHAR(50) NOT NULL, TRIGGER_NAME VARCHAR(50) NOT NULL, JOB_GROUP VARCHAR(50) NOT NULL, JOB_NAME VARCHAR(50) NOT NULL, TRIGGER_TYPE SMALLINT NOT NULL, SCHEDULE BLOB(5000), VOLATILE SMALLINT, CALENDAR_NAME VARCHAR(50), DESCRIPTION VARCHAR(100), NEXT_FIRE_TIME TIMESTAMP, PREV_FIRE_TIME TIMESTAMP, PRIORITY SMALLINT, TRIGGER_STATE SMALLINT, MISFIRE_INSTR SMALLINT, JOB_DATA BLOB(5000), PROPERTY0 VARCHAR(50), PROPERTY1 VARCHAR(50), PROPERTY2 VARCHAR(50), PRIMARY KEY (TRIGGER_NAME, TRIGGER_GROUP));

-- DROP TABLE RBT_CALENDARS;
CREATE TABLE RBT_CALENDARS(NAME VARCHAR(50) NOT NULL, CALENDAR BLOB(5000), PRIMARY KEY (NAME));
